### ISSUE TITLE
ActorImageError: Image not found at https://abs.twimg.com/sticky/default_profile_images/default_profile_200x200.pn...

### ISSUE THREAD

**Issue by trkw** [soussune/soussune.com#30]
https://sentry.io/soussune/soussune/issues/440315817/

```
ActorImageError: Image not found at https://abs.twimg.com/sticky/default_profile_images/default_profile_200x200.png. (actor: lovalotta)
  at ActorImageError (./components/ActorIcon.vue?fd03:23:1)
  at imgError (./components/ActorIcon.vue?fd03:35:1)
  at q (/bundles/54c9f267c81f2243344e9e0163c238891c7edd29.js:1:4109)
  at e (/bundles/54c9f267c81f2243344e9e0163c238891c7edd29.js:1:9231)
  at h (/bundles/54c9f267c81f2243344e9e0163c238891c7edd29.js:1:876870)
```

**Comment by trkw** [comment]
[午後5時24分] miyaoka: sticky無かったのは
[午後5時24分] miyaoka: twitterのサーバーが調子悪かったのかと

とのことなので、close
