### ISSUE TITLE
Register feed in webpack plugin

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.com#72]
RSS feedについて、現状static下に書き出してgitignoreで除外しているが、webpackのビルドプラグインに登録して書き出してもらったほうが管理的に良さそう

例）
https://github.com/miyaoka/content-cache-demo/blob/14f34f2d3ed19e9b60d71125cb89a44397c95ab1/modules/contents.js#L68-L79

**Comment by miyaoka** [comment]
たぶんobjectのまま書き出そうとしてると思うので、xmlの内容をstring化すれば大丈夫かと（上の例でもjsonオブジェクトをstringifyしてる）

**Comment by trkw** [comment]
xmlをstringifyしてる例をメモ、ただし以下をいれただけでは以下のようなエラーとなり動作しなかったことを確認。

https://github.com/1000ch/xml-stringify

```
✖ fatal TypeError: Cannot read property 'children' of undefined
at createXML (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/xml-stringify/index.js:36:14)
   at stringify (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/xml-stringify/index.js:64:10)
   at ModuleContainer.feedModule (/Users/trkw/src/github.com/soussune/soussune.com/src/modules/rss.js:31:15)
   at Promise (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/nuxt/dist/nuxt.js:530:30)
   at new Promise (<anonymous>)
   at ModuleContainer.addModule (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/nuxt/dist/nuxt.js:528:12)
   at promise.then (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/nuxt/dist/nuxt.js:127:43)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:160:7)
   at Function.Module.runMain (module.js:703:11)
   at startup (bootstrap_node.js:193:16)
   at bootstrap_node.js:617:3
```

https://github.com/cburgmer/xmlserializer

```
✖ fatal TypeError: Cannot read property 'replace' of undefined
at removeInvalidCharacters (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/xmlserializer/xmlserializer.js:13:24)
   at Object.serializeToString (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/xmlserializer/xmlserializer.js:126:20)
   at ModuleContainer.feedModule (/Users/trkw/src/github.com/soussune/soussune.com/src/modules/rss.js:32:29)
   at Promise (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/nuxt/dist/nuxt.js:530:30)
   at new Promise (<anonymous>)
   at ModuleContainer.addModule (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/nuxt/dist/nuxt.js:528:12)
   at promise.then (/Users/trkw/src/github.com/soussune/soussune.com/node_modules/nuxt/dist/nuxt.js:127:43)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:160:7)
   at Function.Module.runMain (module.js:703:11)
   at startup (bootstrap_node.js:193:16)
   at bootstrap_node.js:617:3
```

**Comment by trkw** [comment]
了解。出来たのであげてみる
